### ISSUE TITLE
Implement the register page

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-unicef-angola#4]
- [x] For Add a Child (bottom right corner) opens registration form (https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/9)
- [ ] [Update the search](https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/25)
- [x] REMOVE the Due filter (Bell Icon)
- [x] [Update text next to avatar/picture](https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/6)
- [x] Update the age in Age column
](https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/7)
<img width="345" alt="Screen Shot 2020-10-14 at 11 32 11 AM" src="https://user-images.githubusercontent.com/20777928/95963931-f2297180-0e10-11eb-9c63-411156f450a2.png">

**Comment by msschroeder** [comment]
Closing created issue #25 for the search icon on the bottom
